server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/cloud
